### PR TITLE
upd documentation

### PR DESCRIPTION
**Pull request by Anton-Latukha**
The main idea is to clarify the Syslog message severities of RFC, so people would set the message levels properly.

Provided links to RFC and explanation and examples in Arch Wiki (which put there previously).

Also simplified explanation of string termination.

For documentation - I use the free editing (Wiki) model. If documentation changes are wanted, please add them.

### CODE REVIEW

**Comment by Anton-Latukha** [comment]
@peti 

Good day to you.

Please note that more detailed explanations are helpful for young developers to understand what message classifies to what level.

And that this is only docs, CI fails for project internal reasons.

---

If you would want to use GitHub CI - there is good example: I keep a special project for this: https://github.com/haskell-nix/haskell-with-nixpkgs, and main projects in `haskell-nix` are examples of use.

Overall - it is not that hard to maintain GitHub CI, but of course the `haskell-ci` allows to automate some stuff for Travis.

**Comment by peti** [comment]
Hi Anton!

Thank you very much for your suggestions. I have to admit that I'm hesitant to merge them because I don't feel like all your edits are actually improvements. Some are, for sure, but I cannot easily merge those changes that I like and those that I don't, which puts the entire PR on hold somehow.

Furthermore, your changes break `doctest`, which is why the CI build fails.

**Comment by Anton-Latukha** [comment]
Me, lazy hypocrite, was bamboozled by the partial CI builds and some other stuff, thought that Haddock was not parsing the unordinary URLs.

What was the real cause - is that `haddock` does not allow at least in some cases to put argument documentation before the argument.

The patch now is split into a lot of parts. Be free to change it or do whatever with it.
I am Ok to just close it, just was trying to uncover more information on message classifications in the Linux systems.

**Comment by Anton-Latukha** [comment]
Now it builts properly: https://travis-ci.org/github/peti/hsyslog/builds/751018553

Also note that Travis does `.org -> .com` migration, this project is on `.org`, the accounts/project CI pipelines probably would be migrated by themselves, but also that domain switch has some differences in the Travis backend, `.com` allows some additional features.

**Comment by Anton-Latukha** [comment]
Ok.
Considering this as discussed and closed.

**Pull request closed without merging**
